version: "3.9"
services:
  backend:
    image: "nidhallourimi/spring-boot-fullstack:8.11.2021.19.39.5"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
