version: "3.9"
services:
  backend:
    image: "nidhallourimi/spring-boot-fullstack:9.11.2021.14.57.22"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
